### PR TITLE
joomla-cypress test suite

### PR DESCRIPTION
**Pull request by muhme**
Pull Request for Issue #14

Cypress-based test suite for `joomla-cypress` NPM module. Each Cypress custom command is tested at least once.

Update to Cypress 13.16.0 is needed to use `defaultBrowser` in cypress config.

The `joomla-cypress` test suite was tested headless with:
* Own target
  * Windows 11 24H2 + Laragon + IPv4 + Joomla 5.2-dev
  * macOS 15.1 Intel + MariaDB + Apache + IPv4 + Joomla 5.2-dev
* JBT
  * Windows 11 24H2 + WSL 2 Ubuntu + MariaDB-MySQLi + IPv4 + Joomla 4.4-dev, 5.2-dev, 5.3-dev, 6.0-dev
  * Ubuntu 24.04 + MariaDB-MySQLi + IPv4 + Joomla 4.4-dev, 5.2-dev, 5.3-dev, 6.0-dev
  * macOS 15.1 Apple Silicon
    * IPv4 + MariaDB-MySQLi + Joomla 4.4-dev, 5.2-dev, 5.3-dev, 6.0-dev
    * IPv6 + Joomla 5.2-dev + MySQL-MySQLi, MySQL-PDO, MariaDB-MySQLi, MariaDB-PDO, PostgreSQL-PDO, MySQL-MySQLi-Socket, MySQL-PDO-Socket, MariaDB-MySQLi-Socket, Mariadb-PDO-Socket, PostgreSQL-PDO-Socket
  * macOS 15.1 Intel + MariaDB-MySQLi + IPv4 + Joomla 4.4-dev, 5.2-dev, 5.3-dev, 6.0-dev
  
  :warning: You have to install patch #37 first or `installJoomlaMultilingualSite` and a lot of sub-sequent tests will fail.
---
:bell: 19 Dec 2024 PM: Directory level `tests` inserted before the Cypress tests, directory `cypress` removed and tests are moved into `e2e` sub-folder. JBT adopted too and you have to use version >= 2.1.16.

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks, should the cypress folder not be named tests?

**Comment by muhme** [comment]
I did indeed start with `tests`. Later I renamed it to `cypress` because `cypress/fixtures` and `cypress/screenshots` were needed. Renaming is not possible, I think. We can leave it at `cypress` or move `cypress` to `tests/cypress` and `./cypress.config.*` to `tests`?

**Comment by laoneo** [comment]
A common setup in many projects is that you have a src folder with the code and a tests folder with all the testing stuff. I would like to keep it that way. How it is now, it is not possible to distinguish what is testing code and what is library code.

**Comment by laoneo** [comment]
Thanks you very much!

**Pull request merged**
