### PR TITLE
Issue #9 fix functions

### PR DESCRIPTION
**Pull request by muhme**
Fixed several issues when using joomla-cypress for multilingual Joomla plus module installation.

For each problem there is a separate commit with detailed comments.

Tested against dockerized Joomla 4.3.4 and Joomla 5.0.0-rc with local Cypress 13.3.0. 

There are no differences seen in between using different browsers (Chrome v118, Electron v114 or Firefox v118).

Please note that I used Cypress for the first time and I tested it only on MacOS 14.0 (Sonoma).

### CODE REVIEW

**Comment by HLeithner** [comment]
@laoneo can you have a look?

**Comment by laoneo** [comment]
Looks good. To actually see if the changes work, it would probably make sense to create a pr in the main repo, pointing to this pr. As we don't have any system test actually installing an extension, these ones can't be tested.

**Comment by muhme** [comment]
Now that the official Docker images are available, I have successfully retested the Joomla installation, a module installation and some basic module configuration with:

- Joomla! 4.4.0 Stable [ Pamoja ] 17-October-2023 16:00 GMT :white_check_mark:
- Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT :white_check_mark:

**Comment by laoneo** [comment]
Nice. Would love to see some extension installer tests in the cms repo. Can you make a pr for it in the main repo?

**Pull request merged**
